name: CI
on:
  push:
  pull_request:
    branches: [ main ]
env:
  # For tput
  CI: 1
  TERM: xterm
jobs:
  test-with-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        run: ./init.sh
      - name: Lint
        run: ./lint.sh
      - name: Check
        run: ./check.sh
      - name: Build
        run: ./build.sh
      - name: Tests
        run: ./test.sh